version: '3.8'
services:
  web:
    build: .
    ports:
      - "8070:80"
    volumes:
      - ./src:/var/www/html
      # - ./apache-vhost.conf:/etc/apache2/sites-available/000-default.conf
    # environment:
    #   - SOME_ENV_VAR=somevalue
